### ISSUE TITLE
Task #1: Complete Unity Essentials training course

### ISSUE THREAD

**Issue by fronchetti** [vcuse/spinola#1]
Before diving into VR development, you must learn the basics first. As a starting point, we recommend the completion of the "Unity Essentials" training course available at https://learn.unity.com/.

Essential steps to complete this task:
- [ ] Create a Unity ID (in other words, an account) at https://id.unity.com/
- [ ] Open the Unity Essentials course at https://learn.unity.com/pathway/unity-essentials
- [ ] Complete the course and post your progress on this issue
- [ ] Feel free to explore the other courses of the Unity Learn platform, such as the VR Development one at https://learn.unity.com/pathway/vr-development

If you face any problems, don't hesitate to contact me at [fronchettl@vcu.edu](mailto:fronchettl@vcu.edu).

**Comment by adamhusse818** [comment]
Completed first part of Unity Essentials course. Installed unity, learned the unity hub, learned to create first project, and used the microgame feature to learn some basics in the unity editor.

**Comment by adamhusse818** [comment]
Began second part, "Explore Unity", of Unity Essentials. Created and manipulated 3D structures, created child and parent relationships, and created structures with these 3D objects.

**Comment by lidianycs** [comment]
I created an ID, installed Unity and Unity Hub. Learning how to use it with the Lego project.

**Comment by adamhusse818** [comment]
Made progress on the "Explore Unity" section by implementing a "the floor is lava" game. I also finished the part for scripting, so I got an introduction to coding in Unity.

**Comment by adamhusse818** [comment]
Completed the "Explore Unity" section of the course. Learned about 2D scenes, using physics in 2D, using sprites, using audio, and some of the processes behind development in Unity.

**Comment by adamhusse818** [comment]
Finished the Unity Essentials pathway. I plan on taking a look at the VR Development and Junior Programmer pathways to sharpen my skills in these areas as well.
