### ISSUE TITLE
Task #3: Implement basic scripts in Unity

### ISSUE THREAD

**Issue by fronchetti** [vcuse/spinola#3]
Now that you have your Unity project running and the [Japanese School](https://assetstore.unity.com/packages/3d/environments/japanese-school-stylized-221256) working, it is your moment to spend some time coding. 

Using the Demo scene from the Japanese School, create scripts that:

- [ ] Allow the player to fly around the school scene using the WASD keyboard keys. 
- [ ] Teleport the player to specific locations of the school using specific keys of the keyboard (e.g., Q, W, and E).
- [ ] Increase the Vignette intensity effect when the player is moving. 
_HINT: To do so, in the hierarchy section of the Demo scene, look for the "Sky and Fog Volume" game object. You will be able to increase the Vignette intensity effect by increasing the intensity value of the Volume component of this object. If you don't know how to do so, first try to learn how to manipulate the values of the game object's components in your scene._ 
- [ ] Create a simple system (it could be, for example, a UI interface of keyboard interactions) that allows the player to control the sunlight intensity of the scene.
_HINT: This can be done by allowing the player to set the intensity value of the light component available in the Sun game object of the Demo scene._
- [ ] Upload your C# code to a GitHub repository with a README file describing what you did. Don't upload the Japanese School asset on GitHub as this would fall into a copyright violation.

Requirements:
- Try to use different script files for the functionalities requested above.
- Make sure that your code is clear and documented. For example, if you created a method to implement the teleport functionality, make sure that you write this method (and the docstrings) in a way that anyone with experience in programming can easily understand. 

If you face any problems, don't hesitate to contact me at [fronchettl@vcu.edu](mailto:fronchettl@vcu.edu).

**Comment by adamhusse818** [comment]
My GitHub repository is linked here: https://github.com/adamhusse818/IntroductionProject
